/*
DO NOT EDIT!

This file is autogenerated by setup.py.  To edit its contents,
edit doc/docstrings.py
*/

#ifndef __DOCSTRINGS_H__
#define __DOCSTRINGS_H__

void fill_docstrings(void);

extern char doc_DistortionLookupTable[369];
extern char doc_K[152];
extern char doc_M[56];
extern char doc_Sip[1023];
extern char doc_Tabprm[232];
extern char doc_UnitConverter[2222];
extern char doc_Wcs[506];
extern char doc_Wcsprm[1985];
extern char doc_Wtbarr[201];
extern char doc_a[228];
extern char doc_a_order[94];
extern char doc_all_pix2sky[1204];
extern char doc_alt[236];
extern char doc_ap[231];
extern char doc_ap_order[96];
extern char doc_axis_types[916];
extern char doc_b[228];
extern char doc_b_order[94];
extern char doc_bp[231];
extern char doc_bp_order[96];
extern char doc_cd[1054];
extern char doc_cdelt[308];
extern char doc_cel_offset[153];
extern char doc_celfix[136];
extern char doc_cname[76];
extern char doc_colax[91];
extern char doc_colnum[235];
extern char doc_convert[120];
extern char doc_coord[290];
extern char doc_copy[39];
extern char doc_cpdis1[105];
extern char doc_cpdis2[105];
extern char doc_crder[123];
extern char doc_crota[1050];
extern char doc_crpix[88];
extern char doc_crval[93];
extern char doc_crval_tabprm[131];
extern char doc_csyer[132];
extern char doc_ctype[228];
extern char doc_cubeface[1232];
extern char doc_cunit[1270];
extern char doc_cylfix[127];
extern char doc_data[78];
extern char doc_data_wtbarr[51];
extern char doc_dateavg[152];
extern char doc_dateobs[133];
extern char doc_datfix[477];
extern char doc_delta[207];
extern char doc_det2im[57];
extern char doc_det2im1[102];
extern char doc_det2im2[102];
extern char doc_dims[110];
extern char doc_equinox[242];
extern char doc_extlev[72];
extern char doc_extnam[73];
extern char doc_extrema[451];
extern char doc_extver[72];
extern char doc_find_all_wcs[858];
extern char doc_fix[1448];
extern char doc_get_cdelt[451];
extern char doc_get_offset[103];
extern char doc_get_pc[390];
extern char doc_get_ps[369];
extern char doc_get_pv[659];
extern char doc_has_cd[859];
extern char doc_has_cdi_ja[102];
extern char doc_has_crota[620];
extern char doc_has_crotaia[107];
extern char doc_has_pc[182];
extern char doc_has_pci_ja[102];
extern char doc_have[163];
extern char doc_i[40];
extern char doc_imgpix_matrix[143];
extern char doc_is_unity[108];
extern char doc_kind[129];
extern char doc_lat[89];
extern char doc_latpole[75];
extern char doc_lattyp[227];
extern char doc_lng[90];
extern char doc_lngtyp[228];
extern char doc_lonpole[76];
extern char doc_m[58];
extern char doc_map[953];
extern char doc_mix[4678];
extern char doc_mjdavg[195];
extern char doc_mjdobs[195];
extern char doc_name[74];
extern char doc_naxis[760];
extern char doc_nc[121];
extern char doc_ndim[66];
extern char doc_obsgeo[186];
extern char doc_offset[47];
extern char doc_p0[208];
extern char doc_p2s[1833];
extern char doc_p4_pix2foc[556];
extern char doc_pc[1121];
extern char doc_phi0[295];
extern char doc_pix2foc[558];
extern char doc_piximg_matrix[128];
extern char doc_power[49];
extern char doc_print_contents[209];
extern char doc_print_contents_tabprm[223];
extern char doc_radesys[77];
extern char doc_restfrq[94];
extern char doc_restwav[94];
extern char doc_row[39];
extern char doc_s2p[1722];
extern char doc_scale[56];
extern char doc_sense[194];
extern char doc_set[1220];
extern char doc_set_ps[360];
extern char doc_set_pv[359];
extern char doc_set_tabprm[346];
extern char doc_sip[83];
extern char doc_sip_foc2pix[573];
extern char doc_sip_pix2foc[571];
extern char doc_spcfix[237];
extern char doc_spec[68];
extern char doc_specsys[151];
extern char doc_sptr[1354];
extern char doc_ssysobs[238];
extern char doc_ssyssrc[110];
extern char doc_sub[3108];
extern char doc_tab[83];
extern char doc_theta0[294];
extern char doc_to_header[2122];
extern char doc_ttype[107];
extern char doc_unitfix[1008];
extern char doc_velangl[169];
extern char doc_velosys[294];
extern char doc_want[161];
extern char doc_wcs[81];
extern char doc_zsource[98];

#endif

