version: 2

build:
  os: ubuntu-20.04
  apt_packages:
    - graphviz
  tools:
    python: "3.9"
  jobs:
    post_install:
      - pip install -U git+https://github.com/ayshih/sphinx@svg_urls_3.5.4

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

# Install regular dependencies.
# Then, install special pinning for RTD.
python:
  system_packages: false
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

# Don't build any extra formats
formats: []
