version: 2

build:
  image: latest

# Install regular dependencies.
# Then, install special pinning for RTD.
python:
  version: 3.8
  system_packages: false
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

# Don't build any extra formats
formats: []
