version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_checkout:
      - git fetch --shallow-since=2023-01-01  || true
    pre_install:
      - git update-index --assume-unchanged docs/conf.py docs/rtd_environment.yaml
    post_install:
      - pip install -U git+https://github.com/sphinx-doc/sphinx
      - pip install -U git+https://github.com/ayshih/sphinx-automodapi@broken_links

conda:
  environment: docs/rtd_environment.yaml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

# Install regular dependencies.
# Then, install special pinning for RTD.
python:
  system_packages: false
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

# Don't build any extra formats
formats: []
