version: 2

build:
  image: latest

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

# Install regular dependencies.
# Then, install special pinning for RTD.
python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all
    - requirements: docs/rtd_requirements.txt

# Don't build any extra formats
formats: []
