version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    pre_install:
      - git update-index --assume-unchanged docs/conf.py uv.lock
    install:
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --extra docs --extra all

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

# Don't build any extra formats
formats: []
