.. Known projects

.. PROJECTNAME placeholders
.. _PROJECTNAME: http://neuroimaging.scipy.org
.. _`PROJECTNAME github`: http://github.com/nipy
.. _`PROJECTNAME mailing list`: http://projects.scipy.org/mailman/listinfo/nipy-devel

.. numpy
.. _numpy: http://numpy.scipy.org
.. _`numpy github`: http://github.com/numpy/numpy
.. _`numpy mailing list`: http://mail.python.org/mailman/listinfo/numpy-discussion

.. scipy
.. _scipy: http://www.scipy.org
.. _`scipy github`: http://github.com/scipy/scipy
.. _`scipy mailing list`: http://mail.python.org/mailman/listinfo/scipy-dev

.. ipython
.. _ipython: http://ipython.scipy.org
.. _`ipython github`: http://github.com/ipython/ipython
.. _`ipython mailing list`: http://mail.python.org/mailman/listinfo/IPython-dev

.. pip
.. _pip: http://www.pip-installer.org/en/latest/

.. virtualenv
.. _virtualenv: http://pypi.python.org/pypi/virtualenv
.. _virtualenvwrapper: http://pypi.python.org/pypi/virtualenvwrapper
.. _virtualenvwrapper-csh: https://bitbucket.org/embray/virtualenvwrapper-csh
.. _virtualenvwrapper-win: https://github.com/davidmarble/virtualenvwrapper-win
.. _venv: http://docs.python.org/dev/library/venv.html

.. conda
.. _conda: http://conda.pydata.org/docs/

.. pytest
.. _py.test: https://pytest.org/en/latest/

.. pychecker
.. _pychecker: https://pypi.python.org/pypi/PyChecker
