# Licensed under a 3-clause BSD style license - see LICENSE.rst
from __future__ import (absolute_import, division, print_function, unicode_literals)


# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'DA395940D76FFEB6A68EA2DB16FC015D'
    
_lr_action_items = {'HOUR':([2,8,10,17,18,21,23,24,31,32,33,34,42,],[-15,12,-14,20,-16,-9,-12,-8,-13,-9,-10,-9,-11,]),'DEGREE':([2,8,10,17,18,21,23,24,31,32,33,34,42,],[-15,13,-14,19,-16,-9,-12,-8,-13,-9,-10,-9,-11,]),'SIGN':([0,],[5,]),'SECOND':([2,8,10,17,18,21,23,24,31,32,33,34,40,41,42,],[-15,14,-14,-17,-16,-9,-12,-8,-13,-9,-10,-9,43,44,-11,]),'COLON':([17,34,],[22,39,]),'UINT':([0,5,11,17,19,20,21,22,35,37,39,],[-7,-6,17,21,25,28,32,34,32,32,32,]),'SIMPLE_UNIT':([2,8,10,17,18,21,23,24,31,32,33,34,42,],[-15,15,-14,-17,-16,-9,-12,-8,-13,-9,-10,-9,-11,]),'UFLOAT':([0,5,11,17,19,20,21,22,35,37,39,],[-7,-6,18,24,27,30,24,24,24,24,24,]),'MINUTE':([2,8,10,17,18,21,23,24,25,27,28,30,31,32,33,34,42,],[-15,16,-14,-17,-16,-9,-12,-8,35,36,37,38,-13,-9,-10,-9,-11,]),'$end':([1,2,3,4,6,7,8,9,10,12,13,14,15,16,17,18,19,20,21,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,40,41,42,43,44,],[-4,-15,0,-5,-3,-1,-32,-2,-14,-24,-31,-34,-33,-35,-17,-16,-25,-18,-9,-12,-8,-9,-26,-8,-9,-19,-8,-13,-9,-10,-9,-27,-28,-20,-21,-29,-22,-11,-30,-23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'arcminute':([0,],[1,]),'angle':([0,],[3,]),'simple':([0,],[4,]),'arcsecond':([0,],[6,]),'hms':([0,],[7,]),'generic':([0,],[8,]),'dms':([0,],[9,]),'colon':([0,],[10,]),'spaced':([0,],[2,]),'sign':([0,],[11,]),'ufloat':([17,19,20,21,22,35,37,39,],[23,26,29,31,33,40,41,42,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> angle","S'",1,None,None,None),
  ('angle -> hms','angle',1,'p_angle','angle_utilities.py',121),
  ('angle -> dms','angle',1,'p_angle','angle_utilities.py',122),
  ('angle -> arcsecond','angle',1,'p_angle','angle_utilities.py',123),
  ('angle -> arcminute','angle',1,'p_angle','angle_utilities.py',124),
  ('angle -> simple','angle',1,'p_angle','angle_utilities.py',125),
  ('sign -> SIGN','sign',1,'p_sign','angle_utilities.py',131),
  ('sign -> <empty>','sign',0,'p_sign','angle_utilities.py',132),
  ('ufloat -> UFLOAT','ufloat',1,'p_ufloat','angle_utilities.py',141),
  ('ufloat -> UINT','ufloat',1,'p_ufloat','angle_utilities.py',142),
  ('colon -> sign UINT COLON ufloat','colon',4,'p_colon','angle_utilities.py',148),
  ('colon -> sign UINT COLON UINT COLON ufloat','colon',6,'p_colon','angle_utilities.py',149),
  ('spaced -> sign UINT ufloat','spaced',3,'p_spaced','angle_utilities.py',158),
  ('spaced -> sign UINT UINT ufloat','spaced',4,'p_spaced','angle_utilities.py',159),
  ('generic -> colon','generic',1,'p_generic','angle_utilities.py',168),
  ('generic -> spaced','generic',1,'p_generic','angle_utilities.py',169),
  ('generic -> sign UFLOAT','generic',2,'p_generic','angle_utilities.py',170),
  ('generic -> sign UINT','generic',2,'p_generic','angle_utilities.py',171),
  ('hms -> sign UINT HOUR','hms',3,'p_hms','angle_utilities.py',180),
  ('hms -> sign UINT HOUR ufloat','hms',4,'p_hms','angle_utilities.py',181),
  ('hms -> sign UINT HOUR UINT MINUTE','hms',5,'p_hms','angle_utilities.py',182),
  ('hms -> sign UINT HOUR UFLOAT MINUTE','hms',5,'p_hms','angle_utilities.py',183),
  ('hms -> sign UINT HOUR UINT MINUTE ufloat','hms',6,'p_hms','angle_utilities.py',184),
  ('hms -> sign UINT HOUR UINT MINUTE ufloat SECOND','hms',7,'p_hms','angle_utilities.py',185),
  ('hms -> generic HOUR','hms',2,'p_hms','angle_utilities.py',186),
  ('dms -> sign UINT DEGREE','dms',3,'p_dms','angle_utilities.py',199),
  ('dms -> sign UINT DEGREE ufloat','dms',4,'p_dms','angle_utilities.py',200),
  ('dms -> sign UINT DEGREE UINT MINUTE','dms',5,'p_dms','angle_utilities.py',201),
  ('dms -> sign UINT DEGREE UFLOAT MINUTE','dms',5,'p_dms','angle_utilities.py',202),
  ('dms -> sign UINT DEGREE UINT MINUTE ufloat','dms',6,'p_dms','angle_utilities.py',203),
  ('dms -> sign UINT DEGREE UINT MINUTE ufloat SECOND','dms',7,'p_dms','angle_utilities.py',204),
  ('dms -> generic DEGREE','dms',2,'p_dms','angle_utilities.py',205),
  ('simple -> generic','simple',1,'p_simple','angle_utilities.py',218),
  ('simple -> generic SIMPLE_UNIT','simple',2,'p_simple','angle_utilities.py',219),
  ('arcsecond -> generic SECOND','arcsecond',2,'p_arcsecond','angle_utilities.py',228),
  ('arcminute -> generic MINUTE','arcminute',2,'p_arcminute','angle_utilities.py',234),
]
