# Licensed under a 3-clause BSD style license - see LICENSE.rst

# ruff: noqa: PLC2401

from astropy.units import IrreducibleUnit, PrefixUnit, Unit

AU: Unit
Bethe: Unit
DN: IrreducibleUnit
EAU: PrefixUnit
EJy: PrefixUnit
ER: PrefixUnit
Eadu: PrefixUnit
Eau: PrefixUnit
Ebeam: PrefixUnit
Ebin: PrefixUnit
Echan: PrefixUnit
Ecount: PrefixUnit
Ect: PrefixUnit
Elyr: PrefixUnit
Epc: PrefixUnit
Eph: PrefixUnit
Ephoton: PrefixUnit
GAU: PrefixUnit
GJy: PrefixUnit
GR: PrefixUnit
Gadu: PrefixUnit
Gau: PrefixUnit
Gbeam: PrefixUnit
Gbin: PrefixUnit
Gchan: PrefixUnit
Gcount: PrefixUnit
Gct: PrefixUnit
Glyr: PrefixUnit
Gpc: PrefixUnit
Gph: PrefixUnit
Gphoton: PrefixUnit
Jansky: Unit
Jy: Unit
L_sun: Unit
Lsun: Unit
MAU: PrefixUnit
MJy: PrefixUnit
MR: PrefixUnit
M_earth: Unit
M_jup: Unit
M_jupiter: Unit
M_sun: Unit
Madu: PrefixUnit
Mau: PrefixUnit
Mbeam: PrefixUnit
Mbin: PrefixUnit
Mchan: PrefixUnit
Mcount: PrefixUnit
Mct: PrefixUnit
Mearth: Unit
Mjup: Unit
Mjupiter: Unit
Mlyr: PrefixUnit
Mpc: PrefixUnit
Mph: PrefixUnit
Mphoton: PrefixUnit
Msun: Unit
PAU: PrefixUnit
PJy: PrefixUnit
PR: PrefixUnit
Padu: PrefixUnit
Pau: PrefixUnit
Pbeam: PrefixUnit
Pbin: PrefixUnit
Pchan: PrefixUnit
Pcount: PrefixUnit
Pct: PrefixUnit
Plyr: PrefixUnit
Ppc: PrefixUnit
Pph: PrefixUnit
Pphoton: PrefixUnit
QAU: PrefixUnit
QJy: PrefixUnit
QR: PrefixUnit
Qadu: PrefixUnit
Qau: PrefixUnit
Qbeam: PrefixUnit
Qbin: PrefixUnit
Qchan: PrefixUnit
Qcount: PrefixUnit
Qct: PrefixUnit
Qlyr: PrefixUnit
Qpc: PrefixUnit
Qph: PrefixUnit
Qphoton: PrefixUnit
R: Unit
RAU: PrefixUnit
RJy: PrefixUnit
RR: PrefixUnit
R_earth: Unit
R_jup: Unit
R_jupiter: Unit
R_sun: Unit
Radu: PrefixUnit
Rau: PrefixUnit
Rayleigh: Unit
Rbeam: PrefixUnit
Rbin: PrefixUnit
Rchan: PrefixUnit
Rcount: PrefixUnit
Rct: PrefixUnit
Rearth: Unit
Rjup: Unit
Rjupiter: Unit
Rlyr: PrefixUnit
Rpc: PrefixUnit
Rph: PrefixUnit
Rphoton: PrefixUnit
Rsun: Unit
Sun: IrreducibleUnit
TAU: PrefixUnit
TJy: PrefixUnit
TR: PrefixUnit
Tadu: PrefixUnit
Tau: PrefixUnit
Tbeam: PrefixUnit
Tbin: PrefixUnit
Tchan: PrefixUnit
Tcount: PrefixUnit
Tct: PrefixUnit
Tlyr: PrefixUnit
Tpc: PrefixUnit
Tph: PrefixUnit
Tphoton: PrefixUnit
YAU: PrefixUnit
YJy: PrefixUnit
YR: PrefixUnit
Yadu: PrefixUnit
Yau: PrefixUnit
Ybeam: PrefixUnit
Ybin: PrefixUnit
Ychan: PrefixUnit
Ycount: PrefixUnit
Yct: PrefixUnit
Ylyr: PrefixUnit
Ypc: PrefixUnit
Yph: PrefixUnit
Yphoton: PrefixUnit
ZAU: PrefixUnit
ZJy: PrefixUnit
ZR: PrefixUnit
Zadu: PrefixUnit
Zau: PrefixUnit
Zbeam: PrefixUnit
Zbin: PrefixUnit
Zchan: PrefixUnit
Zcount: PrefixUnit
Zct: PrefixUnit
Zlyr: PrefixUnit
Zpc: PrefixUnit
Zph: PrefixUnit
Zphoton: PrefixUnit
aAU: PrefixUnit
aJy: PrefixUnit
aR: PrefixUnit
aadu: PrefixUnit
aau: PrefixUnit
abeam: PrefixUnit
abin: PrefixUnit
achan: PrefixUnit
acount: PrefixUnit
act: PrefixUnit
adu: IrreducibleUnit
alyr: PrefixUnit
apc: PrefixUnit
aph: PrefixUnit
aphoton: PrefixUnit
astronomical_unit: Unit
attoJansky: PrefixUnit
attoRayleigh: PrefixUnit
attoastronomical_unit: PrefixUnit
attocount: PrefixUnit
attojansky: PrefixUnit
attolightyear: PrefixUnit
attoparsec: PrefixUnit
attophoton: PrefixUnit
attorayleigh: PrefixUnit
au: Unit
beam: IrreducibleUnit
bethe: Unit
bin: IrreducibleUnit
cAU: PrefixUnit
cJy: PrefixUnit
cR: PrefixUnit
cadu: PrefixUnit
cau: PrefixUnit
cbeam: PrefixUnit
cbin: PrefixUnit
cchan: PrefixUnit
ccount: PrefixUnit
cct: PrefixUnit
centiJansky: PrefixUnit
centiRayleigh: PrefixUnit
centiastronomical_unit: PrefixUnit
centicount: PrefixUnit
centijansky: PrefixUnit
centilightyear: PrefixUnit
centiparsec: PrefixUnit
centiphoton: PrefixUnit
centirayleigh: PrefixUnit
chan: IrreducibleUnit
clyr: PrefixUnit
count: IrreducibleUnit
cpc: PrefixUnit
cph: PrefixUnit
cphoton: PrefixUnit
ct: IrreducibleUnit
dAU: PrefixUnit
dJy: PrefixUnit
dR: PrefixUnit
daAU: PrefixUnit
daJy: PrefixUnit
daR: PrefixUnit
daadu: PrefixUnit
daau: PrefixUnit
dabeam: PrefixUnit
dabin: PrefixUnit
dachan: PrefixUnit
dacount: PrefixUnit
dact: PrefixUnit
dadu: PrefixUnit
dalyr: PrefixUnit
dapc: PrefixUnit
daph: PrefixUnit
daphoton: PrefixUnit
dau: PrefixUnit
dbeam: PrefixUnit
dbin: PrefixUnit
dchan: PrefixUnit
dcount: PrefixUnit
dct: PrefixUnit
decaJansky: PrefixUnit
decaRayleigh: PrefixUnit
decaastronomical_unit: PrefixUnit
decacount: PrefixUnit
decajansky: PrefixUnit
decalightyear: PrefixUnit
decaparsec: PrefixUnit
decaphoton: PrefixUnit
decarayleigh: PrefixUnit
deciJansky: PrefixUnit
deciRayleigh: PrefixUnit
deciastronomical_unit: PrefixUnit
decicount: PrefixUnit
decijansky: PrefixUnit
decilightyear: PrefixUnit
deciparsec: PrefixUnit
deciphoton: PrefixUnit
decirayleigh: PrefixUnit
dekaJansky: PrefixUnit
dekaRayleigh: PrefixUnit
dekaastronomical_unit: PrefixUnit
dekacount: PrefixUnit
dekajansky: PrefixUnit
dekalightyear: PrefixUnit
dekaparsec: PrefixUnit
dekaphoton: PrefixUnit
dekarayleigh: PrefixUnit
dlyr: PrefixUnit
dn: IrreducibleUnit
dpc: PrefixUnit
dph: PrefixUnit
dphoton: PrefixUnit
earthMass: Unit
earthRad: Unit
electron: IrreducibleUnit
exaJansky: PrefixUnit
exaRayleigh: PrefixUnit
exaastronomical_unit: PrefixUnit
exacount: PrefixUnit
exajansky: PrefixUnit
exalightyear: PrefixUnit
exaparsec: PrefixUnit
exaphoton: PrefixUnit
exarayleigh: PrefixUnit
fAU: PrefixUnit
fJy: PrefixUnit
fR: PrefixUnit
fadu: PrefixUnit
fau: PrefixUnit
fbeam: PrefixUnit
fbin: PrefixUnit
fchan: PrefixUnit
fcount: PrefixUnit
fct: PrefixUnit
femtoJansky: PrefixUnit
femtoRayleigh: PrefixUnit
femtoastronomical_unit: PrefixUnit
femtocount: PrefixUnit
femtojansky: PrefixUnit
femtolightyear: PrefixUnit
femtoparsec: PrefixUnit
femtophoton: PrefixUnit
femtorayleigh: PrefixUnit
flyr: PrefixUnit
foe: Unit
fpc: PrefixUnit
fph: PrefixUnit
fphoton: PrefixUnit
gigaJansky: PrefixUnit
gigaRayleigh: PrefixUnit
gigaastronomical_unit: PrefixUnit
gigacount: PrefixUnit
gigajansky: PrefixUnit
gigalightyear: PrefixUnit
gigaparsec: PrefixUnit
gigaphoton: PrefixUnit
gigarayleigh: PrefixUnit
hAU: PrefixUnit
hJy: PrefixUnit
hR: PrefixUnit
hadu: PrefixUnit
hau: PrefixUnit
hbeam: PrefixUnit
hbin: PrefixUnit
hchan: PrefixUnit
hcount: PrefixUnit
hct: PrefixUnit
hectoJansky: PrefixUnit
hectoRayleigh: PrefixUnit
hectoastronomical_unit: PrefixUnit
hectocount: PrefixUnit
hectojansky: PrefixUnit
hectolightyear: PrefixUnit
hectoparsec: PrefixUnit
hectophoton: PrefixUnit
hectorayleigh: PrefixUnit
hlyr: PrefixUnit
hpc: PrefixUnit
hph: PrefixUnit
hphoton: PrefixUnit
jansky: Unit
jupiterMass: Unit
jupiterRad: Unit
kAU: PrefixUnit
kJy: PrefixUnit
kR: PrefixUnit
kadu: PrefixUnit
kau: PrefixUnit
kbeam: PrefixUnit
kbin: PrefixUnit
kchan: PrefixUnit
kcount: PrefixUnit
kct: PrefixUnit
kiloJansky: PrefixUnit
kiloRayleigh: PrefixUnit
kiloastronomical_unit: PrefixUnit
kilocount: PrefixUnit
kilojansky: PrefixUnit
kilolightyear: PrefixUnit
kiloparsec: PrefixUnit
kilophoton: PrefixUnit
kilorayleigh: PrefixUnit
klyr: PrefixUnit
kpc: PrefixUnit
kph: PrefixUnit
kphoton: PrefixUnit
lightsecond: Unit
lightyear: Unit
lsec: Unit
lyr: Unit
mAU: PrefixUnit
mJy: PrefixUnit
mR: PrefixUnit
madu: PrefixUnit
mau: PrefixUnit
mbeam: PrefixUnit
mbin: PrefixUnit
mchan: PrefixUnit
mcount: PrefixUnit
mct: PrefixUnit
megaJansky: PrefixUnit
megaRayleigh: PrefixUnit
megaastronomical_unit: PrefixUnit
megacount: PrefixUnit
megajansky: PrefixUnit
megalightyear: PrefixUnit
megaparsec: PrefixUnit
megaphoton: PrefixUnit
megarayleigh: PrefixUnit
microJansky: PrefixUnit
microRayleigh: PrefixUnit
microastronomical_unit: PrefixUnit
microcount: PrefixUnit
microjansky: PrefixUnit
microlightyear: PrefixUnit
microparsec: PrefixUnit
microphoton: PrefixUnit
microrayleigh: PrefixUnit
milliJansky: PrefixUnit
milliRayleigh: PrefixUnit
milliastronomical_unit: PrefixUnit
millicount: PrefixUnit
millijansky: PrefixUnit
millilightyear: PrefixUnit
milliparsec: PrefixUnit
milliphoton: PrefixUnit
millirayleigh: PrefixUnit
mlyr: PrefixUnit
mpc: PrefixUnit
mph: PrefixUnit
mphoton: PrefixUnit
nAU: PrefixUnit
nJy: PrefixUnit
nR: PrefixUnit
nadu: PrefixUnit
nanoJansky: PrefixUnit
nanoRayleigh: PrefixUnit
nanoastronomical_unit: PrefixUnit
nanocount: PrefixUnit
nanojansky: PrefixUnit
nanolightyear: PrefixUnit
nanoparsec: PrefixUnit
nanophoton: PrefixUnit
nanorayleigh: PrefixUnit
nau: PrefixUnit
nbeam: PrefixUnit
nbin: PrefixUnit
nchan: PrefixUnit
ncount: PrefixUnit
nct: PrefixUnit
nlyr: PrefixUnit
npc: PrefixUnit
nph: PrefixUnit
nphoton: PrefixUnit
pAU: PrefixUnit
pJy: PrefixUnit
pR: PrefixUnit
padu: PrefixUnit
parsec: Unit
pau: PrefixUnit
pbeam: PrefixUnit
pbin: PrefixUnit
pc: Unit
pchan: PrefixUnit
petaJansky: PrefixUnit
petaRayleigh: PrefixUnit
petaastronomical_unit: PrefixUnit
petacount: PrefixUnit
petajansky: PrefixUnit
petalightyear: PrefixUnit
petaparsec: PrefixUnit
petaphoton: PrefixUnit
petarayleigh: PrefixUnit
ph: IrreducibleUnit
photon: IrreducibleUnit
picoJansky: PrefixUnit
picoRayleigh: PrefixUnit
picoastronomical_unit: PrefixUnit
picocount: PrefixUnit
picojansky: PrefixUnit
picolightyear: PrefixUnit
picoparsec: PrefixUnit
picophoton: PrefixUnit
picorayleigh: PrefixUnit
plyr: PrefixUnit
ppc: PrefixUnit
pph: PrefixUnit
pphoton: PrefixUnit
qAU: PrefixUnit
qJy: PrefixUnit
qR: PrefixUnit
qadu: PrefixUnit
qau: PrefixUnit
qbeam: PrefixUnit
qbin: PrefixUnit
qchan: PrefixUnit
qcount: PrefixUnit
qct: PrefixUnit
qlyr: PrefixUnit
qpc: PrefixUnit
qph: PrefixUnit
qphoton: PrefixUnit
quectoJansky: PrefixUnit
quectoRayleigh: PrefixUnit
quectoastronomical_unit: PrefixUnit
quectocount: PrefixUnit
quectojansky: PrefixUnit
quectolightyear: PrefixUnit
quectoparsec: PrefixUnit
quectophoton: PrefixUnit
quectorayleigh: PrefixUnit
quettaJansky: PrefixUnit
quettaRayleigh: PrefixUnit
quettaastronomical_unit: PrefixUnit
quettacount: PrefixUnit
quettajansky: PrefixUnit
quettalightyear: PrefixUnit
quettaparsec: PrefixUnit
quettaphoton: PrefixUnit
quettarayleigh: PrefixUnit
rAU: PrefixUnit
rJy: PrefixUnit
rR: PrefixUnit
radu: PrefixUnit
rau: PrefixUnit
rayleigh: Unit
rbeam: PrefixUnit
rbin: PrefixUnit
rchan: PrefixUnit
rcount: PrefixUnit
rct: PrefixUnit
rlyr: PrefixUnit
ronnaJansky: PrefixUnit
ronnaRayleigh: PrefixUnit
ronnaastronomical_unit: PrefixUnit
ronnacount: PrefixUnit
ronnajansky: PrefixUnit
ronnalightyear: PrefixUnit
ronnaparsec: PrefixUnit
ronnaphoton: PrefixUnit
ronnarayleigh: PrefixUnit
rontoJansky: PrefixUnit
rontoRayleigh: PrefixUnit
rontoastronomical_unit: PrefixUnit
rontocount: PrefixUnit
rontojansky: PrefixUnit
rontolightyear: PrefixUnit
rontoparsec: PrefixUnit
rontophoton: PrefixUnit
rontorayleigh: PrefixUnit
rpc: PrefixUnit
rph: PrefixUnit
rphoton: PrefixUnit
solLum: Unit
solMass: Unit
solRad: Unit
teraJansky: PrefixUnit
teraRayleigh: PrefixUnit
teraastronomical_unit: PrefixUnit
teracount: PrefixUnit
terajansky: PrefixUnit
teralightyear: PrefixUnit
teraparsec: PrefixUnit
teraphoton: PrefixUnit
terarayleigh: PrefixUnit
uAU: PrefixUnit
uJy: PrefixUnit
uR: PrefixUnit
uadu: PrefixUnit
uau: PrefixUnit
ubeam: PrefixUnit
ubin: PrefixUnit
uchan: PrefixUnit
ucount: PrefixUnit
uct: PrefixUnit
ulyr: PrefixUnit
upc: PrefixUnit
uph: PrefixUnit
uphoton: PrefixUnit
yAU: PrefixUnit
yJy: PrefixUnit
yR: PrefixUnit
yadu: PrefixUnit
yau: PrefixUnit
ybeam: PrefixUnit
ybin: PrefixUnit
ychan: PrefixUnit
ycount: PrefixUnit
yct: PrefixUnit
ylyr: PrefixUnit
yoctoJansky: PrefixUnit
yoctoRayleigh: PrefixUnit
yoctoastronomical_unit: PrefixUnit
yoctocount: PrefixUnit
yoctojansky: PrefixUnit
yoctolightyear: PrefixUnit
yoctoparsec: PrefixUnit
yoctophoton: PrefixUnit
yoctorayleigh: PrefixUnit
yottaJansky: PrefixUnit
yottaRayleigh: PrefixUnit
yottaastronomical_unit: PrefixUnit
yottacount: PrefixUnit
yottajansky: PrefixUnit
yottalightyear: PrefixUnit
yottaparsec: PrefixUnit
yottaphoton: PrefixUnit
yottarayleigh: PrefixUnit
ypc: PrefixUnit
yph: PrefixUnit
yphoton: PrefixUnit
zAU: PrefixUnit
zJy: PrefixUnit
zR: PrefixUnit
zadu: PrefixUnit
zau: PrefixUnit
zbeam: PrefixUnit
zbin: PrefixUnit
zchan: PrefixUnit
zcount: PrefixUnit
zct: PrefixUnit
zeptoJansky: PrefixUnit
zeptoRayleigh: PrefixUnit
zeptoastronomical_unit: PrefixUnit
zeptocount: PrefixUnit
zeptojansky: PrefixUnit
zeptolightyear: PrefixUnit
zeptoparsec: PrefixUnit
zeptophoton: PrefixUnit
zeptorayleigh: PrefixUnit
zettaJansky: PrefixUnit
zettaRayleigh: PrefixUnit
zettaastronomical_unit: PrefixUnit
zettacount: PrefixUnit
zettajansky: PrefixUnit
zettalightyear: PrefixUnit
zettaparsec: PrefixUnit
zettaphoton: PrefixUnit
zettarayleigh: PrefixUnit
zlyr: PrefixUnit
zpc: PrefixUnit
zph: PrefixUnit
zphoton: PrefixUnit
μAU: PrefixUnit
μJy: PrefixUnit
μR: PrefixUnit
μadu: PrefixUnit
μau: PrefixUnit
μbeam: PrefixUnit
μbin: PrefixUnit
μchan: PrefixUnit
μcount: PrefixUnit
μct: PrefixUnit
μlyr: PrefixUnit
μpc: PrefixUnit
μph: PrefixUnit
μphoton: PrefixUnit
