# Licensed under a 3-clause BSD style license - see LICENSE.rst

# ruff: noqa: PLC2401

from astropy.units import IrreducibleUnit, PrefixUnit, Unit

Ba: Unit
Barye: Unit
Bi: Unit
Biot: Unit
C: Unit
D: Unit
Debye: Unit
EBa: PrefixUnit
ED: PrefixUnit
EG: PrefixUnit
EGal: PrefixUnit
EOe: PrefixUnit
EP: PrefixUnit
ESt: PrefixUnit
Edyn: PrefixUnit
Eerg: PrefixUnit
Ek: PrefixUnit
Fr: Unit
Franklin: Unit
G: Unit
GBa: PrefixUnit
GD: PrefixUnit
GG: PrefixUnit
GGal: PrefixUnit
GOe: PrefixUnit
GP: PrefixUnit
GSt: PrefixUnit
Gal: Unit
Gauss: Unit
Gdyn: PrefixUnit
Gerg: PrefixUnit
Gk: PrefixUnit
K: IrreducibleUnit
Kayser: Unit
MBa: PrefixUnit
MD: PrefixUnit
MG: PrefixUnit
MGal: PrefixUnit
MOe: PrefixUnit
MP: PrefixUnit
MSt: PrefixUnit
Maxwell: Unit
Mdyn: PrefixUnit
Merg: PrefixUnit
Mk: PrefixUnit
Mx: Unit
Oe: Unit
Oersted: Unit
P: Unit
PBa: PrefixUnit
PD: PrefixUnit
PG: PrefixUnit
PGal: PrefixUnit
POe: PrefixUnit
PP: PrefixUnit
PSt: PrefixUnit
Pdyn: PrefixUnit
Perg: PrefixUnit
Pk: PrefixUnit
QBa: PrefixUnit
QD: PrefixUnit
QG: PrefixUnit
QGal: PrefixUnit
QOe: PrefixUnit
QP: PrefixUnit
QSt: PrefixUnit
Qdyn: PrefixUnit
Qerg: PrefixUnit
Qk: PrefixUnit
RBa: PrefixUnit
RD: PrefixUnit
RG: PrefixUnit
RGal: PrefixUnit
ROe: PrefixUnit
RP: PrefixUnit
RSt: PrefixUnit
Rdyn: PrefixUnit
Rerg: PrefixUnit
Rk: PrefixUnit
St: Unit
TBa: PrefixUnit
TD: PrefixUnit
TG: PrefixUnit
TGal: PrefixUnit
TOe: PrefixUnit
TP: PrefixUnit
TSt: PrefixUnit
Tdyn: PrefixUnit
Terg: PrefixUnit
Tk: PrefixUnit
YBa: PrefixUnit
YD: PrefixUnit
YG: PrefixUnit
YGal: PrefixUnit
YOe: PrefixUnit
YP: PrefixUnit
YSt: PrefixUnit
Ydyn: PrefixUnit
Yerg: PrefixUnit
Yk: PrefixUnit
ZBa: PrefixUnit
ZD: PrefixUnit
ZG: PrefixUnit
ZGal: PrefixUnit
ZOe: PrefixUnit
ZP: PrefixUnit
ZSt: PrefixUnit
Zdyn: PrefixUnit
Zerg: PrefixUnit
Zk: PrefixUnit
aBa: PrefixUnit
aD: PrefixUnit
aG: PrefixUnit
aGal: PrefixUnit
aOe: PrefixUnit
aP: PrefixUnit
aSt: PrefixUnit
abA: Unit
abC: Unit
abampere: Unit
abcoulomb: Unit
adyn: PrefixUnit
aerg: PrefixUnit
ak: PrefixUnit
attoBarye: PrefixUnit
attoDebye: PrefixUnit
attoGauss: PrefixUnit
attoKayser: PrefixUnit
attoOersted: PrefixUnit
attobarye: PrefixUnit
attodebye: PrefixUnit
attodyne: PrefixUnit
attogal: PrefixUnit
attogauss: PrefixUnit
attokayser: PrefixUnit
attooersted: PrefixUnit
attopoise: PrefixUnit
attostokes: PrefixUnit
barye: Unit
cBa: PrefixUnit
cD: PrefixUnit
cG: PrefixUnit
cGal: PrefixUnit
cOe: PrefixUnit
cP: PrefixUnit
cSt: PrefixUnit
cd: IrreducibleUnit
cdyn: PrefixUnit
centiBarye: PrefixUnit
centiDebye: PrefixUnit
centiGauss: PrefixUnit
centiKayser: PrefixUnit
centiOersted: PrefixUnit
centibarye: PrefixUnit
centidebye: PrefixUnit
centidyne: PrefixUnit
centigal: PrefixUnit
centigauss: PrefixUnit
centikayser: PrefixUnit
centioersted: PrefixUnit
centipoise: PrefixUnit
centistokes: PrefixUnit
cerg: PrefixUnit
ck: PrefixUnit
cm: Unit
dBa: PrefixUnit
dD: PrefixUnit
dG: PrefixUnit
dGal: PrefixUnit
dOe: PrefixUnit
dP: PrefixUnit
dSt: PrefixUnit
daBa: PrefixUnit
daD: PrefixUnit
daG: PrefixUnit
daGal: PrefixUnit
daOe: PrefixUnit
daP: PrefixUnit
daSt: PrefixUnit
dadyn: PrefixUnit
daerg: PrefixUnit
dak: PrefixUnit
ddyn: PrefixUnit
debye: Unit
decaBarye: PrefixUnit
decaDebye: PrefixUnit
decaGauss: PrefixUnit
decaKayser: PrefixUnit
decaOersted: PrefixUnit
decabarye: PrefixUnit
decadebye: PrefixUnit
decadyne: PrefixUnit
decagal: PrefixUnit
decagauss: PrefixUnit
decakayser: PrefixUnit
decaoersted: PrefixUnit
decapoise: PrefixUnit
decastokes: PrefixUnit
deciBarye: PrefixUnit
deciDebye: PrefixUnit
deciGauss: PrefixUnit
deciKayser: PrefixUnit
deciOersted: PrefixUnit
decibarye: PrefixUnit
decidebye: PrefixUnit
decidyne: PrefixUnit
decigal: PrefixUnit
decigauss: PrefixUnit
decikayser: PrefixUnit
decioersted: PrefixUnit
decipoise: PrefixUnit
decistokes: PrefixUnit
deg_C: IrreducibleUnit
dekaBarye: PrefixUnit
dekaDebye: PrefixUnit
dekaGauss: PrefixUnit
dekaKayser: PrefixUnit
dekaOersted: PrefixUnit
dekabarye: PrefixUnit
dekadebye: PrefixUnit
dekadyne: PrefixUnit
dekagal: PrefixUnit
dekagauss: PrefixUnit
dekakayser: PrefixUnit
dekaoersted: PrefixUnit
dekapoise: PrefixUnit
dekastokes: PrefixUnit
derg: PrefixUnit
dk: PrefixUnit
dyn: Unit
dyne: Unit
erg: Unit
esu: Unit
exaBarye: PrefixUnit
exaDebye: PrefixUnit
exaGauss: PrefixUnit
exaKayser: PrefixUnit
exaOersted: PrefixUnit
exabarye: PrefixUnit
exadebye: PrefixUnit
exadyne: PrefixUnit
exagal: PrefixUnit
exagauss: PrefixUnit
exakayser: PrefixUnit
exaoersted: PrefixUnit
exapoise: PrefixUnit
exastokes: PrefixUnit
fBa: PrefixUnit
fD: PrefixUnit
fG: PrefixUnit
fGal: PrefixUnit
fOe: PrefixUnit
fP: PrefixUnit
fSt: PrefixUnit
fdyn: PrefixUnit
femtoBarye: PrefixUnit
femtoDebye: PrefixUnit
femtoGauss: PrefixUnit
femtoKayser: PrefixUnit
femtoOersted: PrefixUnit
femtobarye: PrefixUnit
femtodebye: PrefixUnit
femtodyne: PrefixUnit
femtogal: PrefixUnit
femtogauss: PrefixUnit
femtokayser: PrefixUnit
femtooersted: PrefixUnit
femtopoise: PrefixUnit
femtostokes: PrefixUnit
ferg: PrefixUnit
fk: PrefixUnit
g: Unit
gal: Unit
gauss: Unit
gigaBarye: PrefixUnit
gigaDebye: PrefixUnit
gigaGauss: PrefixUnit
gigaKayser: PrefixUnit
gigaOersted: PrefixUnit
gigabarye: PrefixUnit
gigadebye: PrefixUnit
gigadyne: PrefixUnit
gigagal: PrefixUnit
gigagauss: PrefixUnit
gigakayser: PrefixUnit
gigaoersted: PrefixUnit
gigapoise: PrefixUnit
gigastokes: PrefixUnit
hBa: PrefixUnit
hD: PrefixUnit
hG: PrefixUnit
hGal: PrefixUnit
hOe: PrefixUnit
hP: PrefixUnit
hSt: PrefixUnit
hdyn: PrefixUnit
hectoBarye: PrefixUnit
hectoDebye: PrefixUnit
hectoGauss: PrefixUnit
hectoKayser: PrefixUnit
hectoOersted: PrefixUnit
hectobarye: PrefixUnit
hectodebye: PrefixUnit
hectodyne: PrefixUnit
hectogal: PrefixUnit
hectogauss: PrefixUnit
hectokayser: PrefixUnit
hectooersted: PrefixUnit
hectopoise: PrefixUnit
hectostokes: PrefixUnit
herg: PrefixUnit
hk: PrefixUnit
k: Unit
kBa: PrefixUnit
kD: PrefixUnit
kG: PrefixUnit
kGal: PrefixUnit
kOe: PrefixUnit
kP: PrefixUnit
kSt: PrefixUnit
kayser: Unit
kdyn: PrefixUnit
kerg: PrefixUnit
kiloBarye: PrefixUnit
kiloDebye: PrefixUnit
kiloGauss: PrefixUnit
kiloKayser: PrefixUnit
kiloOersted: PrefixUnit
kilobarye: PrefixUnit
kilodebye: PrefixUnit
kilodyne: PrefixUnit
kilogal: PrefixUnit
kilogauss: PrefixUnit
kilokayser: PrefixUnit
kilooersted: PrefixUnit
kilopoise: PrefixUnit
kilostokes: PrefixUnit
kk: PrefixUnit
mBa: PrefixUnit
mD: PrefixUnit
mG: PrefixUnit
mGal: PrefixUnit
mOe: PrefixUnit
mP: PrefixUnit
mSt: PrefixUnit
maxwell: Unit
mdyn: PrefixUnit
megaBarye: PrefixUnit
megaDebye: PrefixUnit
megaGauss: PrefixUnit
megaKayser: PrefixUnit
megaOersted: PrefixUnit
megabarye: PrefixUnit
megadebye: PrefixUnit
megadyne: PrefixUnit
megagal: PrefixUnit
megagauss: PrefixUnit
megakayser: PrefixUnit
megaoersted: PrefixUnit
megapoise: PrefixUnit
megastokes: PrefixUnit
merg: PrefixUnit
microBarye: PrefixUnit
microDebye: PrefixUnit
microGauss: PrefixUnit
microKayser: PrefixUnit
microOersted: PrefixUnit
microbarye: PrefixUnit
microdebye: PrefixUnit
microdyne: PrefixUnit
microgal: PrefixUnit
microgauss: PrefixUnit
microkayser: PrefixUnit
microoersted: PrefixUnit
micropoise: PrefixUnit
microstokes: PrefixUnit
milliBarye: PrefixUnit
milliDebye: PrefixUnit
milliGauss: PrefixUnit
milliKayser: PrefixUnit
milliOersted: PrefixUnit
millibarye: PrefixUnit
millidebye: PrefixUnit
millidyne: PrefixUnit
milligal: PrefixUnit
milligauss: PrefixUnit
millikayser: PrefixUnit
millioersted: PrefixUnit
millipoise: PrefixUnit
millistokes: PrefixUnit
mk: PrefixUnit
mol: IrreducibleUnit
nBa: PrefixUnit
nD: PrefixUnit
nG: PrefixUnit
nGal: PrefixUnit
nOe: PrefixUnit
nP: PrefixUnit
nSt: PrefixUnit
nanoBarye: PrefixUnit
nanoDebye: PrefixUnit
nanoGauss: PrefixUnit
nanoKayser: PrefixUnit
nanoOersted: PrefixUnit
nanobarye: PrefixUnit
nanodebye: PrefixUnit
nanodyne: PrefixUnit
nanogal: PrefixUnit
nanogauss: PrefixUnit
nanokayser: PrefixUnit
nanooersted: PrefixUnit
nanopoise: PrefixUnit
nanostokes: PrefixUnit
ndyn: PrefixUnit
nerg: PrefixUnit
nk: PrefixUnit
oersted: Unit
pBa: PrefixUnit
pD: PrefixUnit
pG: PrefixUnit
pGal: PrefixUnit
pOe: PrefixUnit
pP: PrefixUnit
pSt: PrefixUnit
pdyn: PrefixUnit
perg: PrefixUnit
petaBarye: PrefixUnit
petaDebye: PrefixUnit
petaGauss: PrefixUnit
petaKayser: PrefixUnit
petaOersted: PrefixUnit
petabarye: PrefixUnit
petadebye: PrefixUnit
petadyne: PrefixUnit
petagal: PrefixUnit
petagauss: PrefixUnit
petakayser: PrefixUnit
petaoersted: PrefixUnit
petapoise: PrefixUnit
petastokes: PrefixUnit
picoBarye: PrefixUnit
picoDebye: PrefixUnit
picoGauss: PrefixUnit
picoKayser: PrefixUnit
picoOersted: PrefixUnit
picobarye: PrefixUnit
picodebye: PrefixUnit
picodyne: PrefixUnit
picogal: PrefixUnit
picogauss: PrefixUnit
picokayser: PrefixUnit
picooersted: PrefixUnit
picopoise: PrefixUnit
picostokes: PrefixUnit
pk: PrefixUnit
poise: Unit
qBa: PrefixUnit
qD: PrefixUnit
qG: PrefixUnit
qGal: PrefixUnit
qOe: PrefixUnit
qP: PrefixUnit
qSt: PrefixUnit
qdyn: PrefixUnit
qerg: PrefixUnit
qk: PrefixUnit
quectoBarye: PrefixUnit
quectoDebye: PrefixUnit
quectoGauss: PrefixUnit
quectoKayser: PrefixUnit
quectoOersted: PrefixUnit
quectobarye: PrefixUnit
quectodebye: PrefixUnit
quectodyne: PrefixUnit
quectogal: PrefixUnit
quectogauss: PrefixUnit
quectokayser: PrefixUnit
quectooersted: PrefixUnit
quectopoise: PrefixUnit
quectostokes: PrefixUnit
quettaBarye: PrefixUnit
quettaDebye: PrefixUnit
quettaGauss: PrefixUnit
quettaKayser: PrefixUnit
quettaOersted: PrefixUnit
quettabarye: PrefixUnit
quettadebye: PrefixUnit
quettadyne: PrefixUnit
quettagal: PrefixUnit
quettagauss: PrefixUnit
quettakayser: PrefixUnit
quettaoersted: PrefixUnit
quettapoise: PrefixUnit
quettastokes: PrefixUnit
rBa: PrefixUnit
rD: PrefixUnit
rG: PrefixUnit
rGal: PrefixUnit
rOe: PrefixUnit
rP: PrefixUnit
rSt: PrefixUnit
rad: IrreducibleUnit
rdyn: PrefixUnit
rerg: PrefixUnit
rk: PrefixUnit
ronnaBarye: PrefixUnit
ronnaDebye: PrefixUnit
ronnaGauss: PrefixUnit
ronnaKayser: PrefixUnit
ronnaOersted: PrefixUnit
ronnabarye: PrefixUnit
ronnadebye: PrefixUnit
ronnadyne: PrefixUnit
ronnagal: PrefixUnit
ronnagauss: PrefixUnit
ronnakayser: PrefixUnit
ronnaoersted: PrefixUnit
ronnapoise: PrefixUnit
ronnastokes: PrefixUnit
rontoBarye: PrefixUnit
rontoDebye: PrefixUnit
rontoGauss: PrefixUnit
rontoKayser: PrefixUnit
rontoOersted: PrefixUnit
rontobarye: PrefixUnit
rontodebye: PrefixUnit
rontodyne: PrefixUnit
rontogal: PrefixUnit
rontogauss: PrefixUnit
rontokayser: PrefixUnit
rontooersted: PrefixUnit
rontopoise: PrefixUnit
rontostokes: PrefixUnit
s: IrreducibleUnit
sr: Unit
statA: Unit
statC: Unit
statampere: Unit
statcoulomb: Unit
stokes: Unit
teraBarye: PrefixUnit
teraDebye: PrefixUnit
teraGauss: PrefixUnit
teraKayser: PrefixUnit
teraOersted: PrefixUnit
terabarye: PrefixUnit
teradebye: PrefixUnit
teradyne: PrefixUnit
teragal: PrefixUnit
teragauss: PrefixUnit
terakayser: PrefixUnit
teraoersted: PrefixUnit
terapoise: PrefixUnit
terastokes: PrefixUnit
uBa: PrefixUnit
uD: PrefixUnit
uG: PrefixUnit
uGal: PrefixUnit
uOe: PrefixUnit
uP: PrefixUnit
uSt: PrefixUnit
udyn: PrefixUnit
uerg: PrefixUnit
uk: PrefixUnit
yBa: PrefixUnit
yD: PrefixUnit
yG: PrefixUnit
yGal: PrefixUnit
yOe: PrefixUnit
yP: PrefixUnit
ySt: PrefixUnit
ydyn: PrefixUnit
yerg: PrefixUnit
yk: PrefixUnit
yoctoBarye: PrefixUnit
yoctoDebye: PrefixUnit
yoctoGauss: PrefixUnit
yoctoKayser: PrefixUnit
yoctoOersted: PrefixUnit
yoctobarye: PrefixUnit
yoctodebye: PrefixUnit
yoctodyne: PrefixUnit
yoctogal: PrefixUnit
yoctogauss: PrefixUnit
yoctokayser: PrefixUnit
yoctooersted: PrefixUnit
yoctopoise: PrefixUnit
yoctostokes: PrefixUnit
yottaBarye: PrefixUnit
yottaDebye: PrefixUnit
yottaGauss: PrefixUnit
yottaKayser: PrefixUnit
yottaOersted: PrefixUnit
yottabarye: PrefixUnit
yottadebye: PrefixUnit
yottadyne: PrefixUnit
yottagal: PrefixUnit
yottagauss: PrefixUnit
yottakayser: PrefixUnit
yottaoersted: PrefixUnit
yottapoise: PrefixUnit
yottastokes: PrefixUnit
zBa: PrefixUnit
zD: PrefixUnit
zG: PrefixUnit
zGal: PrefixUnit
zOe: PrefixUnit
zP: PrefixUnit
zSt: PrefixUnit
zdyn: PrefixUnit
zeptoBarye: PrefixUnit
zeptoDebye: PrefixUnit
zeptoGauss: PrefixUnit
zeptoKayser: PrefixUnit
zeptoOersted: PrefixUnit
zeptobarye: PrefixUnit
zeptodebye: PrefixUnit
zeptodyne: PrefixUnit
zeptogal: PrefixUnit
zeptogauss: PrefixUnit
zeptokayser: PrefixUnit
zeptooersted: PrefixUnit
zeptopoise: PrefixUnit
zeptostokes: PrefixUnit
zerg: PrefixUnit
zettaBarye: PrefixUnit
zettaDebye: PrefixUnit
zettaGauss: PrefixUnit
zettaKayser: PrefixUnit
zettaOersted: PrefixUnit
zettabarye: PrefixUnit
zettadebye: PrefixUnit
zettadyne: PrefixUnit
zettagal: PrefixUnit
zettagauss: PrefixUnit
zettakayser: PrefixUnit
zettaoersted: PrefixUnit
zettapoise: PrefixUnit
zettastokes: PrefixUnit
zk: PrefixUnit
μBa: PrefixUnit
μD: PrefixUnit
μG: PrefixUnit
μGal: PrefixUnit
μOe: PrefixUnit
μP: PrefixUnit
μSt: PrefixUnit
μdyn: PrefixUnit
μerg: PrefixUnit
μk: PrefixUnit
