# Licensed under a 3-clause BSD style license - see LICENSE.rst

# ruff: noqa: PLC2401

from astropy.units import PrefixUnit, Unit

EearthMass: PrefixUnit
EearthRad: PrefixUnit
EjupiterMass: PrefixUnit
EjupiterRad: PrefixUnit
GearthMass: PrefixUnit
GearthRad: PrefixUnit
GjupiterMass: PrefixUnit
GjupiterRad: PrefixUnit
MearthMass: PrefixUnit
MearthRad: PrefixUnit
MjupiterMass: PrefixUnit
MjupiterRad: PrefixUnit
PearthMass: PrefixUnit
PearthRad: PrefixUnit
PjupiterMass: PrefixUnit
PjupiterRad: PrefixUnit
QearthMass: PrefixUnit
QearthRad: PrefixUnit
QjupiterMass: PrefixUnit
QjupiterRad: PrefixUnit
RearthMass: PrefixUnit
RearthRad: PrefixUnit
RjupiterMass: PrefixUnit
RjupiterRad: PrefixUnit
TearthMass: PrefixUnit
TearthRad: PrefixUnit
TjupiterMass: PrefixUnit
TjupiterRad: PrefixUnit
YearthMass: PrefixUnit
YearthRad: PrefixUnit
YjupiterMass: PrefixUnit
YjupiterRad: PrefixUnit
ZearthMass: PrefixUnit
ZearthRad: PrefixUnit
ZjupiterMass: PrefixUnit
ZjupiterRad: PrefixUnit
aearthMass: PrefixUnit
aearthRad: PrefixUnit
ajupiterMass: PrefixUnit
ajupiterRad: PrefixUnit
attoM_earth: PrefixUnit
attoM_jup: PrefixUnit
attoM_jupiter: PrefixUnit
attoMearth: PrefixUnit
attoMjup: PrefixUnit
attoMjupiter: PrefixUnit
attoR_earth: PrefixUnit
attoR_jup: PrefixUnit
attoR_jupiter: PrefixUnit
attoRearth: PrefixUnit
attoRjup: PrefixUnit
attoRjupiter: PrefixUnit
cearthMass: PrefixUnit
cearthRad: PrefixUnit
centiM_earth: PrefixUnit
centiM_jup: PrefixUnit
centiM_jupiter: PrefixUnit
centiMearth: PrefixUnit
centiMjup: PrefixUnit
centiMjupiter: PrefixUnit
centiR_earth: PrefixUnit
centiR_jup: PrefixUnit
centiR_jupiter: PrefixUnit
centiRearth: PrefixUnit
centiRjup: PrefixUnit
centiRjupiter: PrefixUnit
cjupiterMass: PrefixUnit
cjupiterRad: PrefixUnit
daearthMass: PrefixUnit
daearthRad: PrefixUnit
dajupiterMass: PrefixUnit
dajupiterRad: PrefixUnit
dearthMass: PrefixUnit
dearthRad: PrefixUnit
decaM_earth: PrefixUnit
decaM_jup: PrefixUnit
decaM_jupiter: PrefixUnit
decaMearth: PrefixUnit
decaMjup: PrefixUnit
decaMjupiter: PrefixUnit
decaR_earth: PrefixUnit
decaR_jup: PrefixUnit
decaR_jupiter: PrefixUnit
decaRearth: PrefixUnit
decaRjup: PrefixUnit
decaRjupiter: PrefixUnit
deciM_earth: PrefixUnit
deciM_jup: PrefixUnit
deciM_jupiter: PrefixUnit
deciMearth: PrefixUnit
deciMjup: PrefixUnit
deciMjupiter: PrefixUnit
deciR_earth: PrefixUnit
deciR_jup: PrefixUnit
deciR_jupiter: PrefixUnit
deciRearth: PrefixUnit
deciRjup: PrefixUnit
deciRjupiter: PrefixUnit
dekaM_earth: PrefixUnit
dekaM_jup: PrefixUnit
dekaM_jupiter: PrefixUnit
dekaMearth: PrefixUnit
dekaMjup: PrefixUnit
dekaMjupiter: PrefixUnit
dekaR_earth: PrefixUnit
dekaR_jup: PrefixUnit
dekaR_jupiter: PrefixUnit
dekaRearth: PrefixUnit
dekaRjup: PrefixUnit
dekaRjupiter: PrefixUnit
djupiterMass: PrefixUnit
djupiterRad: PrefixUnit
emu: Unit
exaM_earth: PrefixUnit
exaM_jup: PrefixUnit
exaM_jupiter: PrefixUnit
exaMearth: PrefixUnit
exaMjup: PrefixUnit
exaMjupiter: PrefixUnit
exaR_earth: PrefixUnit
exaR_jup: PrefixUnit
exaR_jupiter: PrefixUnit
exaRearth: PrefixUnit
exaRjup: PrefixUnit
exaRjupiter: PrefixUnit
fearthMass: PrefixUnit
fearthRad: PrefixUnit
femtoM_earth: PrefixUnit
femtoM_jup: PrefixUnit
femtoM_jupiter: PrefixUnit
femtoMearth: PrefixUnit
femtoMjup: PrefixUnit
femtoMjupiter: PrefixUnit
femtoR_earth: PrefixUnit
femtoR_jup: PrefixUnit
femtoR_jupiter: PrefixUnit
femtoRearth: PrefixUnit
femtoRjup: PrefixUnit
femtoRjupiter: PrefixUnit
fjupiterMass: PrefixUnit
fjupiterRad: PrefixUnit
gigaM_earth: PrefixUnit
gigaM_jup: PrefixUnit
gigaM_jupiter: PrefixUnit
gigaMearth: PrefixUnit
gigaMjup: PrefixUnit
gigaMjupiter: PrefixUnit
gigaR_earth: PrefixUnit
gigaR_jup: PrefixUnit
gigaR_jupiter: PrefixUnit
gigaRearth: PrefixUnit
gigaRjup: PrefixUnit
gigaRjupiter: PrefixUnit
hearthMass: PrefixUnit
hearthRad: PrefixUnit
hectoM_earth: PrefixUnit
hectoM_jup: PrefixUnit
hectoM_jupiter: PrefixUnit
hectoMearth: PrefixUnit
hectoMjup: PrefixUnit
hectoMjupiter: PrefixUnit
hectoR_earth: PrefixUnit
hectoR_jup: PrefixUnit
hectoR_jupiter: PrefixUnit
hectoRearth: PrefixUnit
hectoRjup: PrefixUnit
hectoRjupiter: PrefixUnit
hjupiterMass: PrefixUnit
hjupiterRad: PrefixUnit
kearthMass: PrefixUnit
kearthRad: PrefixUnit
kiloM_earth: PrefixUnit
kiloM_jup: PrefixUnit
kiloM_jupiter: PrefixUnit
kiloMearth: PrefixUnit
kiloMjup: PrefixUnit
kiloMjupiter: PrefixUnit
kiloR_earth: PrefixUnit
kiloR_jup: PrefixUnit
kiloR_jupiter: PrefixUnit
kiloRearth: PrefixUnit
kiloRjup: PrefixUnit
kiloRjupiter: PrefixUnit
kjupiterMass: PrefixUnit
kjupiterRad: PrefixUnit
mearthMass: PrefixUnit
mearthRad: PrefixUnit
megaM_earth: PrefixUnit
megaM_jup: PrefixUnit
megaM_jupiter: PrefixUnit
megaMearth: PrefixUnit
megaMjup: PrefixUnit
megaMjupiter: PrefixUnit
megaR_earth: PrefixUnit
megaR_jup: PrefixUnit
megaR_jupiter: PrefixUnit
megaRearth: PrefixUnit
megaRjup: PrefixUnit
megaRjupiter: PrefixUnit
microM_earth: PrefixUnit
microM_jup: PrefixUnit
microM_jupiter: PrefixUnit
microMearth: PrefixUnit
microMjup: PrefixUnit
microMjupiter: PrefixUnit
microR_earth: PrefixUnit
microR_jup: PrefixUnit
microR_jupiter: PrefixUnit
microRearth: PrefixUnit
microRjup: PrefixUnit
microRjupiter: PrefixUnit
milliM_earth: PrefixUnit
milliM_jup: PrefixUnit
milliM_jupiter: PrefixUnit
milliMearth: PrefixUnit
milliMjup: PrefixUnit
milliMjupiter: PrefixUnit
milliR_earth: PrefixUnit
milliR_jup: PrefixUnit
milliR_jupiter: PrefixUnit
milliRearth: PrefixUnit
milliRjup: PrefixUnit
milliRjupiter: PrefixUnit
mjupiterMass: PrefixUnit
mjupiterRad: PrefixUnit
nanoM_earth: PrefixUnit
nanoM_jup: PrefixUnit
nanoM_jupiter: PrefixUnit
nanoMearth: PrefixUnit
nanoMjup: PrefixUnit
nanoMjupiter: PrefixUnit
nanoR_earth: PrefixUnit
nanoR_jup: PrefixUnit
nanoR_jupiter: PrefixUnit
nanoRearth: PrefixUnit
nanoRjup: PrefixUnit
nanoRjupiter: PrefixUnit
nearthMass: PrefixUnit
nearthRad: PrefixUnit
njupiterMass: PrefixUnit
njupiterRad: PrefixUnit
pearthMass: PrefixUnit
pearthRad: PrefixUnit
petaM_earth: PrefixUnit
petaM_jup: PrefixUnit
petaM_jupiter: PrefixUnit
petaMearth: PrefixUnit
petaMjup: PrefixUnit
petaMjupiter: PrefixUnit
petaR_earth: PrefixUnit
petaR_jup: PrefixUnit
petaR_jupiter: PrefixUnit
petaRearth: PrefixUnit
petaRjup: PrefixUnit
petaRjupiter: PrefixUnit
picoM_earth: PrefixUnit
picoM_jup: PrefixUnit
picoM_jupiter: PrefixUnit
picoMearth: PrefixUnit
picoMjup: PrefixUnit
picoMjupiter: PrefixUnit
picoR_earth: PrefixUnit
picoR_jup: PrefixUnit
picoR_jupiter: PrefixUnit
picoRearth: PrefixUnit
picoRjup: PrefixUnit
picoRjupiter: PrefixUnit
pjupiterMass: PrefixUnit
pjupiterRad: PrefixUnit
qearthMass: PrefixUnit
qearthRad: PrefixUnit
qjupiterMass: PrefixUnit
qjupiterRad: PrefixUnit
quectoM_earth: PrefixUnit
quectoM_jup: PrefixUnit
quectoM_jupiter: PrefixUnit
quectoMearth: PrefixUnit
quectoMjup: PrefixUnit
quectoMjupiter: PrefixUnit
quectoR_earth: PrefixUnit
quectoR_jup: PrefixUnit
quectoR_jupiter: PrefixUnit
quectoRearth: PrefixUnit
quectoRjup: PrefixUnit
quectoRjupiter: PrefixUnit
quettaM_earth: PrefixUnit
quettaM_jup: PrefixUnit
quettaM_jupiter: PrefixUnit
quettaMearth: PrefixUnit
quettaMjup: PrefixUnit
quettaMjupiter: PrefixUnit
quettaR_earth: PrefixUnit
quettaR_jup: PrefixUnit
quettaR_jupiter: PrefixUnit
quettaRearth: PrefixUnit
quettaRjup: PrefixUnit
quettaRjupiter: PrefixUnit
rearthMass: PrefixUnit
rearthRad: PrefixUnit
rjupiterMass: PrefixUnit
rjupiterRad: PrefixUnit
ronnaM_earth: PrefixUnit
ronnaM_jup: PrefixUnit
ronnaM_jupiter: PrefixUnit
ronnaMearth: PrefixUnit
ronnaMjup: PrefixUnit
ronnaMjupiter: PrefixUnit
ronnaR_earth: PrefixUnit
ronnaR_jup: PrefixUnit
ronnaR_jupiter: PrefixUnit
ronnaRearth: PrefixUnit
ronnaRjup: PrefixUnit
ronnaRjupiter: PrefixUnit
rontoM_earth: PrefixUnit
rontoM_jup: PrefixUnit
rontoM_jupiter: PrefixUnit
rontoMearth: PrefixUnit
rontoMjup: PrefixUnit
rontoMjupiter: PrefixUnit
rontoR_earth: PrefixUnit
rontoR_jup: PrefixUnit
rontoR_jupiter: PrefixUnit
rontoRearth: PrefixUnit
rontoRjup: PrefixUnit
rontoRjupiter: PrefixUnit
teraM_earth: PrefixUnit
teraM_jup: PrefixUnit
teraM_jupiter: PrefixUnit
teraMearth: PrefixUnit
teraMjup: PrefixUnit
teraMjupiter: PrefixUnit
teraR_earth: PrefixUnit
teraR_jup: PrefixUnit
teraR_jupiter: PrefixUnit
teraRearth: PrefixUnit
teraRjup: PrefixUnit
teraRjupiter: PrefixUnit
uearthMass: PrefixUnit
uearthRad: PrefixUnit
ujupiterMass: PrefixUnit
ujupiterRad: PrefixUnit
yearthMass: PrefixUnit
yearthRad: PrefixUnit
yjupiterMass: PrefixUnit
yjupiterRad: PrefixUnit
yoctoM_earth: PrefixUnit
yoctoM_jup: PrefixUnit
yoctoM_jupiter: PrefixUnit
yoctoMearth: PrefixUnit
yoctoMjup: PrefixUnit
yoctoMjupiter: PrefixUnit
yoctoR_earth: PrefixUnit
yoctoR_jup: PrefixUnit
yoctoR_jupiter: PrefixUnit
yoctoRearth: PrefixUnit
yoctoRjup: PrefixUnit
yoctoRjupiter: PrefixUnit
yottaM_earth: PrefixUnit
yottaM_jup: PrefixUnit
yottaM_jupiter: PrefixUnit
yottaMearth: PrefixUnit
yottaMjup: PrefixUnit
yottaMjupiter: PrefixUnit
yottaR_earth: PrefixUnit
yottaR_jup: PrefixUnit
yottaR_jupiter: PrefixUnit
yottaRearth: PrefixUnit
yottaRjup: PrefixUnit
yottaRjupiter: PrefixUnit
zearthMass: PrefixUnit
zearthRad: PrefixUnit
zeptoM_earth: PrefixUnit
zeptoM_jup: PrefixUnit
zeptoM_jupiter: PrefixUnit
zeptoMearth: PrefixUnit
zeptoMjup: PrefixUnit
zeptoMjupiter: PrefixUnit
zeptoR_earth: PrefixUnit
zeptoR_jup: PrefixUnit
zeptoR_jupiter: PrefixUnit
zeptoRearth: PrefixUnit
zeptoRjup: PrefixUnit
zeptoRjupiter: PrefixUnit
zettaM_earth: PrefixUnit
zettaM_jup: PrefixUnit
zettaM_jupiter: PrefixUnit
zettaMearth: PrefixUnit
zettaMjup: PrefixUnit
zettaMjupiter: PrefixUnit
zettaR_earth: PrefixUnit
zettaR_jup: PrefixUnit
zettaR_jupiter: PrefixUnit
zettaRearth: PrefixUnit
zettaRjup: PrefixUnit
zettaRjupiter: PrefixUnit
zjupiterMass: PrefixUnit
zjupiterRad: PrefixUnit
μearthMass: PrefixUnit
μearthRad: PrefixUnit
μjupiterMass: PrefixUnit
μjupiterRad: PrefixUnit
