# Licensed under a 3-clause BSD style license - see LICENSE.rst

# ruff: noqa: PLC2401

from astropy.units import IrreducibleUnit, PrefixUnit, Unit

B: Unit
Da: Unit
Dalton: Unit
EB: PrefixUnit
ERy: PrefixUnit
Eb: PrefixUnit
Ebarn: PrefixUnit
Ebit: PrefixUnit
Ebyte: PrefixUnit
EeV: PrefixUnit
EiB: PrefixUnit
Eib: PrefixUnit
Eibit: PrefixUnit
Eibyte: PrefixUnit
Epix: PrefixUnit
Epixel: PrefixUnit
Eu: PrefixUnit
Evox: PrefixUnit
Evoxel: PrefixUnit
GB: PrefixUnit
GRy: PrefixUnit
Gb: PrefixUnit
Gbarn: PrefixUnit
Gbit: PrefixUnit
Gbyte: PrefixUnit
GeV: PrefixUnit
GiB: PrefixUnit
Gib: PrefixUnit
Gibit: PrefixUnit
Gibyte: PrefixUnit
Gpix: PrefixUnit
Gpixel: PrefixUnit
Gu: PrefixUnit
Gvox: PrefixUnit
Gvoxel: PrefixUnit
KiB: PrefixUnit
Kib: PrefixUnit
Kibit: PrefixUnit
Kibyte: PrefixUnit
MB: PrefixUnit
MRy: PrefixUnit
M_e: Unit
M_p: Unit
Mb: PrefixUnit
Mbarn: PrefixUnit
Mbit: PrefixUnit
Mbyte: PrefixUnit
MeV: PrefixUnit
MiB: PrefixUnit
Mib: PrefixUnit
Mibit: PrefixUnit
Mibyte: PrefixUnit
Mpix: PrefixUnit
Mpixel: PrefixUnit
Mu: PrefixUnit
Mvox: PrefixUnit
Mvoxel: PrefixUnit
PB: PrefixUnit
PRy: PrefixUnit
Pb: PrefixUnit
Pbarn: PrefixUnit
Pbit: PrefixUnit
Pbyte: PrefixUnit
PeV: PrefixUnit
PiB: PrefixUnit
Pib: PrefixUnit
Pibit: PrefixUnit
Pibyte: PrefixUnit
Ppix: PrefixUnit
Ppixel: PrefixUnit
Pu: PrefixUnit
Pvox: PrefixUnit
Pvoxel: PrefixUnit
QB: PrefixUnit
QRy: PrefixUnit
Qb: PrefixUnit
Qbarn: PrefixUnit
Qbit: PrefixUnit
Qbyte: PrefixUnit
QeV: PrefixUnit
Qpix: PrefixUnit
Qpixel: PrefixUnit
Qu: PrefixUnit
Qvox: PrefixUnit
Qvoxel: PrefixUnit
RB: PrefixUnit
RRy: PrefixUnit
Rb: PrefixUnit
Rbarn: PrefixUnit
Rbit: PrefixUnit
Rbyte: PrefixUnit
ReV: PrefixUnit
Rpix: PrefixUnit
Rpixel: PrefixUnit
Ru: PrefixUnit
Rvox: PrefixUnit
Rvoxel: PrefixUnit
Ry: Unit
TB: PrefixUnit
TRy: PrefixUnit
Tb: PrefixUnit
Tbarn: PrefixUnit
Tbit: PrefixUnit
Tbyte: PrefixUnit
TeV: PrefixUnit
TiB: PrefixUnit
Tib: PrefixUnit
Tibit: PrefixUnit
Tibyte: PrefixUnit
Torr: Unit
Tpix: PrefixUnit
Tpixel: PrefixUnit
Tu: PrefixUnit
Tvox: PrefixUnit
Tvoxel: PrefixUnit
YB: PrefixUnit
YRy: PrefixUnit
Yb: PrefixUnit
Ybarn: PrefixUnit
Ybit: PrefixUnit
Ybyte: PrefixUnit
YeV: PrefixUnit
YiB: PrefixUnit
Yib: PrefixUnit
Yibit: PrefixUnit
Yibyte: PrefixUnit
Ypix: PrefixUnit
Ypixel: PrefixUnit
Yu: PrefixUnit
Yvox: PrefixUnit
Yvoxel: PrefixUnit
ZB: PrefixUnit
ZRy: PrefixUnit
Zb: PrefixUnit
Zbarn: PrefixUnit
Zbit: PrefixUnit
Zbyte: PrefixUnit
ZeV: PrefixUnit
ZiB: PrefixUnit
Zib: PrefixUnit
Zibit: PrefixUnit
Zibyte: PrefixUnit
Zpix: PrefixUnit
Zpixel: PrefixUnit
Zu: PrefixUnit
Zvox: PrefixUnit
Zvoxel: PrefixUnit
aB: PrefixUnit
aRy: PrefixUnit
ab: PrefixUnit
abarn: PrefixUnit
abit: PrefixUnit
abyte: PrefixUnit
aeV: PrefixUnit
apix: PrefixUnit
apixel: PrefixUnit
attoDa: PrefixUnit
attoDalton: PrefixUnit
attobarn: PrefixUnit
attobit: PrefixUnit
attobyte: PrefixUnit
attoelectronvolt: PrefixUnit
attopixel: PrefixUnit
attorydberg: PrefixUnit
attovoxel: PrefixUnit
avox: PrefixUnit
avoxel: PrefixUnit
b: IrreducibleUnit
bar: Unit
barn: Unit
bit: IrreducibleUnit
byte: Unit
cB: PrefixUnit
cRy: PrefixUnit
cb: PrefixUnit
cbarn: PrefixUnit
cbit: PrefixUnit
cbyte: PrefixUnit
ceV: PrefixUnit
centiDa: PrefixUnit
centiDalton: PrefixUnit
centibarn: PrefixUnit
centibit: PrefixUnit
centibyte: PrefixUnit
centielectronvolt: PrefixUnit
centipixel: PrefixUnit
centirydberg: PrefixUnit
centivoxel: PrefixUnit
cpix: PrefixUnit
cpixel: PrefixUnit
cu: PrefixUnit
cvox: PrefixUnit
cvoxel: PrefixUnit
cy: Unit
cycle: Unit
dRy: PrefixUnit
daB: PrefixUnit
daRy: PrefixUnit
dab: PrefixUnit
dabarn: PrefixUnit
dabit: PrefixUnit
dabyte: PrefixUnit
daeV: PrefixUnit
dapix: PrefixUnit
dapixel: PrefixUnit
davox: PrefixUnit
davoxel: PrefixUnit
db: PrefixUnit
dbarn: PrefixUnit
dbit: PrefixUnit
deV: PrefixUnit
decaDa: PrefixUnit
decaDalton: PrefixUnit
decabarn: PrefixUnit
decabit: PrefixUnit
decabyte: PrefixUnit
decaelectronvolt: PrefixUnit
decapixel: PrefixUnit
decarydberg: PrefixUnit
decavoxel: PrefixUnit
deciDa: PrefixUnit
deciDalton: PrefixUnit
decibarn: PrefixUnit
decibit: PrefixUnit
decibyte: PrefixUnit
decielectronvolt: PrefixUnit
decipixel: PrefixUnit
decirydberg: PrefixUnit
decivoxel: PrefixUnit
dekaDa: PrefixUnit
dekaDalton: PrefixUnit
dekabarn: PrefixUnit
dekabit: PrefixUnit
dekabyte: PrefixUnit
dekaelectronvolt: PrefixUnit
dekapixel: PrefixUnit
dekarydberg: PrefixUnit
dekavoxel: PrefixUnit
dpix: PrefixUnit
dpixel: PrefixUnit
du: PrefixUnit
dvox: PrefixUnit
dvoxel: PrefixUnit
eV: Unit
electronvolt: Unit
exaDa: PrefixUnit
exaDalton: PrefixUnit
exabarn: PrefixUnit
exabit: PrefixUnit
exabyte: PrefixUnit
exaelectronvolt: PrefixUnit
exapixel: PrefixUnit
exarydberg: PrefixUnit
exavoxel: PrefixUnit
exbibit: PrefixUnit
exbibyte: PrefixUnit
fB: PrefixUnit
fRy: PrefixUnit
fb: PrefixUnit
fbarn: PrefixUnit
fbit: PrefixUnit
fbyte: PrefixUnit
feV: PrefixUnit
femtoDa: PrefixUnit
femtoDalton: PrefixUnit
femtobarn: PrefixUnit
femtobit: PrefixUnit
femtobyte: PrefixUnit
femtoelectronvolt: PrefixUnit
femtopixel: PrefixUnit
femtorydberg: PrefixUnit
femtovoxel: PrefixUnit
fpix: PrefixUnit
fpixel: PrefixUnit
fu: PrefixUnit
fvox: PrefixUnit
fvoxel: PrefixUnit
gibibit: PrefixUnit
gibibyte: PrefixUnit
gigaDa: PrefixUnit
gigaDalton: PrefixUnit
gigabarn: PrefixUnit
gigabit: PrefixUnit
gigabyte: PrefixUnit
gigaelectronvolt: PrefixUnit
gigapixel: PrefixUnit
gigarydberg: PrefixUnit
gigavoxel: PrefixUnit
hB: PrefixUnit
hRy: PrefixUnit
hb: PrefixUnit
hbarn: PrefixUnit
hbit: PrefixUnit
hbyte: PrefixUnit
heV: PrefixUnit
hectoDa: PrefixUnit
hectoDalton: PrefixUnit
hectobarn: PrefixUnit
hectobit: PrefixUnit
hectobyte: PrefixUnit
hectoelectronvolt: PrefixUnit
hectopixel: PrefixUnit
hectorydberg: PrefixUnit
hectovoxel: PrefixUnit
hpix: PrefixUnit
hpixel: PrefixUnit
hu: PrefixUnit
hvox: PrefixUnit
hvoxel: PrefixUnit
kB: PrefixUnit
kRy: PrefixUnit
kb: PrefixUnit
kbarn: PrefixUnit
kbit: PrefixUnit
kbyte: PrefixUnit
keV: PrefixUnit
kibibit: PrefixUnit
kibibyte: PrefixUnit
kiloDa: PrefixUnit
kiloDalton: PrefixUnit
kilobarn: PrefixUnit
kilobit: PrefixUnit
kilobyte: PrefixUnit
kiloelectronvolt: PrefixUnit
kilopixel: PrefixUnit
kilorydberg: PrefixUnit
kilovoxel: PrefixUnit
kpix: PrefixUnit
kpixel: PrefixUnit
ku: PrefixUnit
kvox: PrefixUnit
kvoxel: PrefixUnit
mB: PrefixUnit
mRy: PrefixUnit
mTorr: PrefixUnit
mb: PrefixUnit
mbar: PrefixUnit
mbarn: PrefixUnit
mbit: PrefixUnit
mbyte: PrefixUnit
meV: PrefixUnit
mebibit: PrefixUnit
mebibyte: PrefixUnit
megaDa: PrefixUnit
megaDalton: PrefixUnit
megabarn: PrefixUnit
megabit: PrefixUnit
megabyte: PrefixUnit
megaelectronvolt: PrefixUnit
megapixel: PrefixUnit
megarydberg: PrefixUnit
megavoxel: PrefixUnit
microDa: PrefixUnit
microDalton: PrefixUnit
microbarn: PrefixUnit
microbit: PrefixUnit
microbyte: PrefixUnit
microelectronvolt: PrefixUnit
micropixel: PrefixUnit
microrydberg: PrefixUnit
microvoxel: PrefixUnit
milliDa: PrefixUnit
milliDalton: PrefixUnit
millibarn: PrefixUnit
millibit: PrefixUnit
millibyte: PrefixUnit
millielectronvolt: PrefixUnit
millipixel: PrefixUnit
millirydberg: PrefixUnit
millitorr: PrefixUnit
millivoxel: PrefixUnit
mpix: PrefixUnit
mpixel: PrefixUnit
mu: PrefixUnit
mvox: PrefixUnit
mvoxel: PrefixUnit
nB: PrefixUnit
nRy: PrefixUnit
nanoDa: PrefixUnit
nanoDalton: PrefixUnit
nanobarn: PrefixUnit
nanobit: PrefixUnit
nanobyte: PrefixUnit
nanoelectronvolt: PrefixUnit
nanopixel: PrefixUnit
nanorydberg: PrefixUnit
nanovoxel: PrefixUnit
nb: PrefixUnit
nbarn: PrefixUnit
nbit: PrefixUnit
nbyte: PrefixUnit
neV: PrefixUnit
npix: PrefixUnit
npixel: PrefixUnit
nu: PrefixUnit
nvox: PrefixUnit
nvoxel: PrefixUnit
pB: PrefixUnit
pRy: PrefixUnit
pb: PrefixUnit
pbarn: PrefixUnit
pbit: PrefixUnit
pbyte: PrefixUnit
peV: PrefixUnit
pebibit: PrefixUnit
pebibyte: PrefixUnit
petaDa: PrefixUnit
petaDalton: PrefixUnit
petabarn: PrefixUnit
petabit: PrefixUnit
petabyte: PrefixUnit
petaelectronvolt: PrefixUnit
petapixel: PrefixUnit
petarydberg: PrefixUnit
petavoxel: PrefixUnit
picoDa: PrefixUnit
picoDalton: PrefixUnit
picobarn: PrefixUnit
picobit: PrefixUnit
picobyte: PrefixUnit
picoelectronvolt: PrefixUnit
picopixel: PrefixUnit
picorydberg: PrefixUnit
picovoxel: PrefixUnit
pix: IrreducibleUnit
pixel: IrreducibleUnit
ppix: PrefixUnit
ppixel: PrefixUnit
pu: PrefixUnit
pvox: PrefixUnit
pvoxel: PrefixUnit
qB: PrefixUnit
qRy: PrefixUnit
qb: PrefixUnit
qbarn: PrefixUnit
qbit: PrefixUnit
qbyte: PrefixUnit
qeV: PrefixUnit
qpix: PrefixUnit
qpixel: PrefixUnit
qu: PrefixUnit
quectoDa: PrefixUnit
quectoDalton: PrefixUnit
quectobarn: PrefixUnit
quectobit: PrefixUnit
quectobyte: PrefixUnit
quectoelectronvolt: PrefixUnit
quectopixel: PrefixUnit
quectorydberg: PrefixUnit
quectovoxel: PrefixUnit
quettaDa: PrefixUnit
quettaDalton: PrefixUnit
quettabarn: PrefixUnit
quettabit: PrefixUnit
quettabyte: PrefixUnit
quettaelectronvolt: PrefixUnit
quettapixel: PrefixUnit
quettarydberg: PrefixUnit
quettavoxel: PrefixUnit
qvox: PrefixUnit
qvoxel: PrefixUnit
rB: PrefixUnit
rRy: PrefixUnit
rb: PrefixUnit
rbarn: PrefixUnit
rbit: PrefixUnit
rbyte: PrefixUnit
reV: PrefixUnit
ronnaDa: PrefixUnit
ronnaDalton: PrefixUnit
ronnabarn: PrefixUnit
ronnabit: PrefixUnit
ronnabyte: PrefixUnit
ronnaelectronvolt: PrefixUnit
ronnapixel: PrefixUnit
ronnarydberg: PrefixUnit
ronnavoxel: PrefixUnit
rontoDa: PrefixUnit
rontoDalton: PrefixUnit
rontobarn: PrefixUnit
rontobit: PrefixUnit
rontobyte: PrefixUnit
rontoelectronvolt: PrefixUnit
rontopixel: PrefixUnit
rontorydberg: PrefixUnit
rontovoxel: PrefixUnit
rpix: PrefixUnit
rpixel: PrefixUnit
ru: PrefixUnit
rvox: PrefixUnit
rvoxel: PrefixUnit
rydberg: Unit
sp: Unit
spat: Unit
tebibit: PrefixUnit
tebibyte: PrefixUnit
teraDa: PrefixUnit
teraDalton: PrefixUnit
terabarn: PrefixUnit
terabit: PrefixUnit
terabyte: PrefixUnit
teraelectronvolt: PrefixUnit
terapixel: PrefixUnit
terarydberg: PrefixUnit
teravoxel: PrefixUnit
torr: Unit
u: Unit
uB: PrefixUnit
uRy: PrefixUnit
ub: PrefixUnit
ubarn: PrefixUnit
ubit: PrefixUnit
ubyte: PrefixUnit
ueV: PrefixUnit
upix: PrefixUnit
upixel: PrefixUnit
uu: PrefixUnit
uvox: PrefixUnit
uvoxel: PrefixUnit
vox: IrreducibleUnit
voxel: IrreducibleUnit
yB: PrefixUnit
yRy: PrefixUnit
yb: PrefixUnit
ybarn: PrefixUnit
ybit: PrefixUnit
ybyte: PrefixUnit
yeV: PrefixUnit
yobibit: PrefixUnit
yobibyte: PrefixUnit
yoctoDa: PrefixUnit
yoctoDalton: PrefixUnit
yoctobarn: PrefixUnit
yoctobit: PrefixUnit
yoctobyte: PrefixUnit
yoctoelectronvolt: PrefixUnit
yoctopixel: PrefixUnit
yoctorydberg: PrefixUnit
yoctovoxel: PrefixUnit
yottaDa: PrefixUnit
yottaDalton: PrefixUnit
yottabarn: PrefixUnit
yottabit: PrefixUnit
yottabyte: PrefixUnit
yottaelectronvolt: PrefixUnit
yottapixel: PrefixUnit
yottarydberg: PrefixUnit
yottavoxel: PrefixUnit
ypix: PrefixUnit
ypixel: PrefixUnit
yu: PrefixUnit
yvox: PrefixUnit
yvoxel: PrefixUnit
zB: PrefixUnit
zRy: PrefixUnit
zb: PrefixUnit
zbarn: PrefixUnit
zbit: PrefixUnit
zbyte: PrefixUnit
zeV: PrefixUnit
zebibit: PrefixUnit
zebibyte: PrefixUnit
zeptoDa: PrefixUnit
zeptoDalton: PrefixUnit
zeptobarn: PrefixUnit
zeptobit: PrefixUnit
zeptobyte: PrefixUnit
zeptoelectronvolt: PrefixUnit
zeptopixel: PrefixUnit
zeptorydberg: PrefixUnit
zeptovoxel: PrefixUnit
zettaDa: PrefixUnit
zettaDalton: PrefixUnit
zettabarn: PrefixUnit
zettabit: PrefixUnit
zettabyte: PrefixUnit
zettaelectronvolt: PrefixUnit
zettapixel: PrefixUnit
zettarydberg: PrefixUnit
zettavoxel: PrefixUnit
zpix: PrefixUnit
zpixel: PrefixUnit
zu: PrefixUnit
zvox: PrefixUnit
zvoxel: PrefixUnit
μB: PrefixUnit
μRy: PrefixUnit
μb: PrefixUnit
μbarn: PrefixUnit
μbit: PrefixUnit
μbyte: PrefixUnit
μeV: PrefixUnit
μpix: PrefixUnit
μpixel: PrefixUnit
μu: PrefixUnit
μvox: PrefixUnit
μvoxel: PrefixUnit
