# Licensed under a 3-clause BSD style license - see LICENSE.rst

# ruff: noqa: PLC2401

from astropy.units import PrefixUnit

EsolLum: PrefixUnit
EsolMass: PrefixUnit
EsolRad: PrefixUnit
GsolLum: PrefixUnit
GsolMass: PrefixUnit
GsolRad: PrefixUnit
MsolLum: PrefixUnit
MsolMass: PrefixUnit
MsolRad: PrefixUnit
PsolLum: PrefixUnit
PsolMass: PrefixUnit
PsolRad: PrefixUnit
QsolLum: PrefixUnit
QsolMass: PrefixUnit
QsolRad: PrefixUnit
RsolLum: PrefixUnit
RsolMass: PrefixUnit
RsolRad: PrefixUnit
TsolLum: PrefixUnit
TsolMass: PrefixUnit
TsolRad: PrefixUnit
YsolLum: PrefixUnit
YsolMass: PrefixUnit
YsolRad: PrefixUnit
ZsolLum: PrefixUnit
ZsolMass: PrefixUnit
ZsolRad: PrefixUnit
asolLum: PrefixUnit
asolMass: PrefixUnit
asolRad: PrefixUnit
attoL_sun: PrefixUnit
attoLsun: PrefixUnit
attoM_sun: PrefixUnit
attoMsun: PrefixUnit
attoR_sun: PrefixUnit
attoRsun: PrefixUnit
centiL_sun: PrefixUnit
centiLsun: PrefixUnit
centiM_sun: PrefixUnit
centiMsun: PrefixUnit
centiR_sun: PrefixUnit
centiRsun: PrefixUnit
csolLum: PrefixUnit
csolMass: PrefixUnit
csolRad: PrefixUnit
dasolLum: PrefixUnit
dasolMass: PrefixUnit
dasolRad: PrefixUnit
decaL_sun: PrefixUnit
decaLsun: PrefixUnit
decaM_sun: PrefixUnit
decaMsun: PrefixUnit
decaR_sun: PrefixUnit
decaRsun: PrefixUnit
deciL_sun: PrefixUnit
deciLsun: PrefixUnit
deciM_sun: PrefixUnit
deciMsun: PrefixUnit
deciR_sun: PrefixUnit
deciRsun: PrefixUnit
dekaL_sun: PrefixUnit
dekaLsun: PrefixUnit
dekaM_sun: PrefixUnit
dekaMsun: PrefixUnit
dekaR_sun: PrefixUnit
dekaRsun: PrefixUnit
dsolLum: PrefixUnit
dsolMass: PrefixUnit
dsolRad: PrefixUnit
exaL_sun: PrefixUnit
exaLsun: PrefixUnit
exaM_sun: PrefixUnit
exaMsun: PrefixUnit
exaR_sun: PrefixUnit
exaRsun: PrefixUnit
femtoL_sun: PrefixUnit
femtoLsun: PrefixUnit
femtoM_sun: PrefixUnit
femtoMsun: PrefixUnit
femtoR_sun: PrefixUnit
femtoRsun: PrefixUnit
fsolLum: PrefixUnit
fsolMass: PrefixUnit
fsolRad: PrefixUnit
gigaL_sun: PrefixUnit
gigaLsun: PrefixUnit
gigaM_sun: PrefixUnit
gigaMsun: PrefixUnit
gigaR_sun: PrefixUnit
gigaRsun: PrefixUnit
hectoL_sun: PrefixUnit
hectoLsun: PrefixUnit
hectoM_sun: PrefixUnit
hectoMsun: PrefixUnit
hectoR_sun: PrefixUnit
hectoRsun: PrefixUnit
hsolLum: PrefixUnit
hsolMass: PrefixUnit
hsolRad: PrefixUnit
kiloL_sun: PrefixUnit
kiloLsun: PrefixUnit
kiloM_sun: PrefixUnit
kiloMsun: PrefixUnit
kiloR_sun: PrefixUnit
kiloRsun: PrefixUnit
ksolLum: PrefixUnit
ksolMass: PrefixUnit
ksolRad: PrefixUnit
megaL_sun: PrefixUnit
megaLsun: PrefixUnit
megaM_sun: PrefixUnit
megaMsun: PrefixUnit
megaR_sun: PrefixUnit
megaRsun: PrefixUnit
microL_sun: PrefixUnit
microLsun: PrefixUnit
microM_sun: PrefixUnit
microMsun: PrefixUnit
microR_sun: PrefixUnit
microRsun: PrefixUnit
milliL_sun: PrefixUnit
milliLsun: PrefixUnit
milliM_sun: PrefixUnit
milliMsun: PrefixUnit
milliR_sun: PrefixUnit
milliRsun: PrefixUnit
msolLum: PrefixUnit
msolMass: PrefixUnit
msolRad: PrefixUnit
nanoL_sun: PrefixUnit
nanoLsun: PrefixUnit
nanoM_sun: PrefixUnit
nanoMsun: PrefixUnit
nanoR_sun: PrefixUnit
nanoRsun: PrefixUnit
nsolLum: PrefixUnit
nsolMass: PrefixUnit
nsolRad: PrefixUnit
petaL_sun: PrefixUnit
petaLsun: PrefixUnit
petaM_sun: PrefixUnit
petaMsun: PrefixUnit
petaR_sun: PrefixUnit
petaRsun: PrefixUnit
picoL_sun: PrefixUnit
picoLsun: PrefixUnit
picoM_sun: PrefixUnit
picoMsun: PrefixUnit
picoR_sun: PrefixUnit
picoRsun: PrefixUnit
psolLum: PrefixUnit
psolMass: PrefixUnit
psolRad: PrefixUnit
qsolLum: PrefixUnit
qsolMass: PrefixUnit
qsolRad: PrefixUnit
quectoL_sun: PrefixUnit
quectoLsun: PrefixUnit
quectoM_sun: PrefixUnit
quectoMsun: PrefixUnit
quectoR_sun: PrefixUnit
quectoRsun: PrefixUnit
quettaL_sun: PrefixUnit
quettaLsun: PrefixUnit
quettaM_sun: PrefixUnit
quettaMsun: PrefixUnit
quettaR_sun: PrefixUnit
quettaRsun: PrefixUnit
ronnaL_sun: PrefixUnit
ronnaLsun: PrefixUnit
ronnaM_sun: PrefixUnit
ronnaMsun: PrefixUnit
ronnaR_sun: PrefixUnit
ronnaRsun: PrefixUnit
rontoL_sun: PrefixUnit
rontoLsun: PrefixUnit
rontoM_sun: PrefixUnit
rontoMsun: PrefixUnit
rontoR_sun: PrefixUnit
rontoRsun: PrefixUnit
rsolLum: PrefixUnit
rsolMass: PrefixUnit
rsolRad: PrefixUnit
teraL_sun: PrefixUnit
teraLsun: PrefixUnit
teraM_sun: PrefixUnit
teraMsun: PrefixUnit
teraR_sun: PrefixUnit
teraRsun: PrefixUnit
usolLum: PrefixUnit
usolMass: PrefixUnit
usolRad: PrefixUnit
yoctoL_sun: PrefixUnit
yoctoLsun: PrefixUnit
yoctoM_sun: PrefixUnit
yoctoMsun: PrefixUnit
yoctoR_sun: PrefixUnit
yoctoRsun: PrefixUnit
yottaL_sun: PrefixUnit
yottaLsun: PrefixUnit
yottaM_sun: PrefixUnit
yottaMsun: PrefixUnit
yottaR_sun: PrefixUnit
yottaRsun: PrefixUnit
ysolLum: PrefixUnit
ysolMass: PrefixUnit
ysolRad: PrefixUnit
zeptoL_sun: PrefixUnit
zeptoLsun: PrefixUnit
zeptoM_sun: PrefixUnit
zeptoMsun: PrefixUnit
zeptoR_sun: PrefixUnit
zeptoRsun: PrefixUnit
zettaL_sun: PrefixUnit
zettaLsun: PrefixUnit
zettaM_sun: PrefixUnit
zettaMsun: PrefixUnit
zettaR_sun: PrefixUnit
zettaRsun: PrefixUnit
zsolLum: PrefixUnit
zsolMass: PrefixUnit
zsolRad: PrefixUnit
μsolLum: PrefixUnit
μsolMass: PrefixUnit
μsolRad: PrefixUnit
