name: Sphinx RC testing

 # We do not run this from cron as the Sphinx RC period is very short, but do trigger it manually when necessary.
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@22ddf09dfabb443adddfb9f861b7d41a787d6b1a  # v3.0.3
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      setenv: |
        ARCH_ON_CI: "normal"
        IS_CRON: "false"
        PY_COLORS: "1"
      submodules: false
      coverage: ''
      libraries: |
        apt:
          - graphviz
      envs: |
        - name: CI with upstream RC including docs dependencies if available
          linux: py314-test-docdeps-predeps

        - name: Build docs with Sphinx RC if available
          linux: build_docs-predeps
          python-version: '3.14'
